version: '3'

services:
  build:
    build: .
    command: sh -c 'sh -c "cd /carapace-completers/carapace && go build -gccgoflags=\"-s -w\" . && upx -9 carapace"'
    volumes:
      - '.:/carapace-completers/'
      - 'go:/go/'
  bash:
    build: .
    command: bash
    volumes:
      - '.:/carapace-completers/'

  elvish:
    build: .
    command: elvish
    volumes:
      - '.:/carapace-completers/'

  fish:
    build: .
    command: fish
    volumes:
      - '.:/carapace-completers/'

  powershell:
    build: .
    command: pwsh
    volumes:
      - '.:/carapace-completers/'

  zsh:
    build: .
    command: zsh
    volumes:
      - '.:/carapace-completers/'

volumes:
  go:
