version: '3'

services:
  build:
    build: .
    command: sh -c 'sh -c "cd /carapace-bin/cmd/carapace && go build -ldflags=\"-s -w\" ."'
    volumes:
      - '.:/carapace-bin/'
      - 'go:/go/'
  bash:
    build: .
    command: bash
    volumes:
      - '.:/carapace-bin/'

  elvish:
    build: .
    command: elvish
    volumes:
      - '.:/carapace-bin/'

  fish:
    build: .
    command: fish
    volumes:
      - '.:/carapace-bin/'
  
  oil: 
    build: .
    command: osh
    volumes:
      - '.:/carapace-bin/'

  powershell:
    build: .
    command: pwsh
    volumes:
      - '.:/carapace-bin/'
  
  xonsh: 
    build: .
    command: xonsh
    volumes:
      - '.:/carapace-bin/'

  zsh:
    build: .
    command: zsh
    volumes:
      - '.:/carapace-bin/'

volumes:
  go:
