version: '3'

services:
  build:
    build: .
    command: sh -c 'sh -c "cd /carapace-completers/carapace && go build -gccgoflags=\"-s -w\" . && upx -9 carapace"'
    volumes:
      - '.:/carapace-completers/'
      - 'go:/go/'
  bash:
    build:
      context: .
      dockerfile: Dockerfile.bash
    volumes:
      - '.:/carapace-completers/'

  elvish:
    build:
      context: .
      dockerfile: Dockerfile.elvish
    volumes:
      - '.:/carapace-completers/'

  fish:
    build:
      context: .
      dockerfile: Dockerfile.fish
    volumes:
      - '.:/carapace-completers/'

  powershell:
    build:
      context: .
      dockerfile: Dockerfile.powershell
    volumes:
      - '.:/carapace-completers/'

  zsh:
    build:
      context: .
      dockerfile: Dockerfile.zsh
    volumes:
      - '.:/carapace-completers/'

volumes:
  go:
