version: 2.1

references:
  workspace: &workspace
    /go/src/github.com/rsteube/carapace-bin

commands:
  run_tests:
    steps:
      - run:
          name: "build"
          command: |
            go get -t -v ./...
            PATH=$PATH:$PWD/bin go test -v ./...
            cd carapace
            go build
            go vet

jobs:
  go-current:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
    working_directory: *workspace
    steps:
      - checkout
      - run_tests
      - run:
          name: "Check formatting"
          command: diff -u <(echo -n) <(gofmt -d -s .)
  go-previous:
    docker:
      - image: circleci/golang:1.14
        environment:
          GO111MODULE: "on"
    working_directory: *workspace
    steps:
      - checkout
      - run_tests
  go-latest:
    docker:
      - image: circleci/golang:latest
    working_directory: *workspace
    steps:
      - checkout
      - run_tests

workflows:
  version: 2
  main:
    jobs:
      - go-current
      - go-previous
      - go-latest
