version: 2.1
workflows:
  main:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  tags:
    jobs:
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/

commands:
  run_tests:
    steps:
      - run:
          name: "build"
          command: |
            go generate ./...
            go get -t -v ./...
            PATH=$PATH:$PWD/bin go test -v ./...
            cd cmd/carapace
            go build
            go vet

jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - run_tests
      - run:
          name: "Check formatting"
          command: diff -u <(echo -n) <(gofmt -d -s .)
      - run:
          name: "staticcheck"
          command: go install honnef.co/go/tools/cmd/staticcheck@2021.1.1 && staticcheck ./...
      - run:
          name: "caralint"
          command: go run ./cmd/caralint completers/*/cmd/*.go
  release:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout 
      - run: cd cmd/carapace && go generate ./... && curl -sL https://git.io/goreleaser | bash
