before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    binary: carapace
    tags:
      - release
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "carapace-bin_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: carapace
    description: "multi-shell multi-command argument completer"
    homepage: "https://github.com/rsteube/carapace-bin"
    license: "MIT"
    tap:
      owner: rsteube
      name: homebrew-tap
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
