name: Go

on:
  pull_request:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    container: ghcr.io/rsteube/carapace
    steps:
      - name: shallow clone
        uses: actions/checkout@v2
        if: "!startsWith(github.ref, 'refs/tags/')"

      - name: deep clone
        uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      
      - name: Generate
        run: go generate ./cmd/...

      - name: Build
        run: ls cmd/ | xargs -I'{}' sh -c "cd ./cmd/{} && go build -v ."

      - uses: actions/upload-artifact@v2
        with:
          name: carapace
          path: ./cmd/carapace/carapace 

      - name: Test
        run: go test -v ./cmd/...

      - name: "Check formatting"
        run: '[ "$(gofmt -d -s . | tee -a /dev/stderr)" = "" ]'

      - name: "staticcheck"
        run: go install honnef.co/go/tools/cmd/staticcheck@latest && staticcheck ./...

      - name: "caralint"
        run: go run ./cmd/caralint completers/*/cmd/*.go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
          GORELEASER_GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

  doc:
    runs-on: ubuntu-latest
    container: ghcr.io/rsteube/carapace
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: carapace
          path: ./cmd/carapace

      - name: "build docs"
        run: |
            sed -i 's/\[output.linkcheck\]/#[output.linkcheck]/' docs/book.toml
            sh .github/completers.sh > docs/src/completers.md
            sh .github/macros.sh > docs/src/specs/macros.md
            mdbook build docs
            sh .github/badge.sh > docs/book/badge.svg

      - name: "push gh-pages"
        if: github.ref == 'refs/heads/master'
        run: |
            cd docs/book/
            git init
            git config user.name rsteube
            git config user.email rsteube@users.noreply.github.com
            git add .
            git commit -m "initial commit [ci skip]"
            git push --force https://rsteube:${GITHUB_TOKEN}@github.com/rsteube/carapace-bin.git master:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
