name: Publish to WinGet

on:
  release:
    types: [released]

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: rsteube.Carapace
          max-versions-to-keep: 5 
          installers-regex: '_windows_amd64\.zip$'
          fork-user: rsteube-bot
          token: ${{ secrets.WINGET_TOKEN }}